SHOW DATABASES;
USE PORTFOLIO;
SHOW TABLES;

#Create new table named as athletes

DROP TABLE IF EXISTS ATHLETES
CREATE TABLE ATHLETES
(
ID INT,
Ath_Name VARCHAR(50),
Sex VARCHAR(5),
Age VARCHAR(5), #On purpose this is not int because the file is not clean
Height VARCHAR(5), #On purpose this is not int because the file is not clean
Weight VARCHAR(5), #On purpose this is not int because the file is not clean
Team VARCHAR(50), 
NOC VARCHAR(5),
Games VARCHAR(50),
Game_Year INT,
Season VARCHAR(50),
City VARCHAR(50),
Sport VARCHAR(50),
Event VARCHAR(500),
Medal VARCHAR(5)
)

#Inserted data using cmd_prompt
SELECT * FROM ATHLETES;
SELECT COUNT(*) FROM ATHLETES;

DROP TABLE IF EXISTS NOC_REGIONS
CREATE TABLE NOC_REGIONS
(
NOC VARCHAR(5),	
region VARCHAR(20),
notes VARCHAR(50)
)

#Inserted data using cmd_prompt
select * from noc_regions

#find the total no of Olympic Games held 
SELECT COUNT(DISTINCT(GAMES)) FROM ATHLETES ;

#list down all the Olympic Games held so far.
SELECT DISTINCT(GAMES) AS GAME, CITY FROM ATHLETES ORDER BY GAMES

#total no of nations who participated in each olympics game
SELECT A.GAMES,COUNT(DISTINCT(B.REGION)) AS TOTAL_COUNTRIES FROM ATHLETES A INNER JOIN NOC_REGIONS B ON A.NOC=B.NOC GROUP BY A.GAMES

#Which year saw the highest and lowest no of countries participating in olympics
SELECT * FROM ATHLETES AS A INNER JOIN NOC_REGIONS B ON A.NOC=B.NOC

SELECT CONCAT(M.GAMES,"-",M.TOTAL_COUNTRIES) as Least_countries FROM (
SELECT A.GAMES,COUNT(DISTINCT(B.REGION)) AS TOTAL_COUNTRIES FROM ATHLETES A INNER JOIN NOC_REGIONS B ON A.NOC=B.NOC GROUP BY A.GAMES) M ORDER BY M.TOTAL_COUNTRIES LIMIT 1

SELECT CONCAT(M.GAMES,"-",M.TOTAL_COUNTRIES) as Most_countries FROM (
SELECT A.GAMES,COUNT(DISTINCT(B.REGION)) AS TOTAL_COUNTRIES FROM ATHLETES A INNER JOIN NOC_REGIONS B ON A.NOC=B.NOC GROUP BY A.GAMES) M ORDER BY M.TOTAL_COUNTRIES DESC LIMIT 1



SELECT * FROM ATHLETES AS A INNER JOIN NOC_REGIONS B ON A.NOC=B.NOC;

SELECT COUNT(DISTINCT(GAMES)) AS GAMES_HELD FROM ATHLETES;

#Which nation has participated in all of the olympic games
SELECT REGION, YEARS_P FROM 
(
SELECT B.REGION,COUNT(DISTINCT(A.GAMES)) AS YEARS_P FROM ATHLETES AS A INNER JOIN NOC_REGIONS B ON A.NOC=B.NOC GROUP BY B.REGION
) M 
WHERE M.YEARS_P=(SELECT COUNT(DISTINCT(GAMES)) FROM ATHLETES)

#SELECT COUNT(DISTINCT(Games)) FROM ATHLETES WHERE SEASON ="Summer"
#SELECT SPORT, COUNT(DISTINCT(GAMES)) AS DG FROM ATHLETES GROUP BY SPORT ORDER BY DG DESC 
#SELECT COUNT(DISTINCT(GAMES)) FROM ATHLETES

#Identify the sport which was played in all summer olympics.
SELECT SPORT,DG FROM 
(
SELECT SPORT, COUNT(DISTINCT(GAMES)) AS DG FROM ATHLETES GROUP BY SPORT ORDER BY DG DESC 
) M
WHERE M.DG=(SELECT COUNT(DISTINCT(Games)) FROM ATHLETES WHERE SEASON ="Summer")


#Identify the sport that was played just once in the oplympics
SELECT SPORT, DG, GAMES FROM (
SELECT SPORT, COUNT(DISTINCT(GAMES)) AS DG, GAMES FROM ATHLETES GROUP BY SPORT ORDER BY DG DESC )
M WHERE M.DG=1

#Fetch the total number of sports played in each olympics
SELECT GAMES, COUNT(DISTINCT(SPORT)) AS PLAYED FROM ATHLETES GROUP BY GAMES ORDER BY PLAYED DESC;

#The oldest athlete to win a gold medal
SELECT ATH_NAME, SEX, AGE, TEAM, GAMES, CITY, SPORT, EVENT, MEDAL FROM ATHLETES WHERE MEDAL='GOLD' AND AGE=(SELECT MAX(AGE) FROM ATHLETES WHERE AGE<"NA" AND MEDAL="GOLD");

#Find the Ratio of male and female athletes participated in all olympic games.
SELECT (SELECT COUNT(SEX) FROM ATHLETES WHERE SEX='F' LIMIT 1)/ (SELECT COUNT(SEX) FROM ATHLETES WHERE SEX='M' LIMIT 1) AS RATIO FROM ATHLETES LIMIT 1;

#Find the top 5 athletes who have won the most gold medals.
SELECT ATH_NAME, TEAM, COUNT(MEDAL) FROM ATHLETES WHERE MEDAL="Gold" GROUP BY ATH_NAME ORDER BY COUNT(MEDAL) DESC LIMIT 5;

#Fetch the top 5 athletes who have won the most medals (gold/silver/bronze).
SELECT ATH_NAME, TEAM, COUNT(MEDAL) FROM 
(
SELECT * FROM ATHLETES WHERE MEDAL IN ('Gold', 'Silver', 'Bronze')
) M GROUP BY ATH_NAME ORDER BY COUNT(MEDAL) DESC LIMIT 5



#Fetch the top 5 most successful countries in olympics. Success is defined by no of medals won.
SELECT M.REGION, COUNT(MEDAL) FROM 
(SELECT A.*,B.REGION FROM ATHLETES A INNER JOIN NOC_REGIONS B ON A.NOC=B.NOC WHERE MEDAL IN ('Gold', 'Silver', 'Bronze'))M GROUP BY M.REGION ORDER BY COUNT(MEDAL) DESC LIMIT 5;


SELECT B.REGION, COUNT(MEDAL)FROM ATHLETES A INNER JOIN NOC_REGIONS B ON A.NOC=B.NOC GROUP BY REGION ORDER BY COUNT(MEDAL) DESC